#!/usr/bin/env bash
set -euo pipefail

BASE_DIR=${BASE_DIR:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}
source "$BASE_DIR/lib/common.sh"

TARGET_HOST=${TARGET_HOST:-syslog.example.net}
TARGET_PORT=${TARGET_PORT:-1514}
RSYSLOG_REMOTE_FILE=${RSYSLOG_REMOTE_FILE:-/etc/rsyslog.d/remote_syslog.conf}

build_rsyslog_conf() {
  cat <<EOF_CONF
# Auto-generated by rsyslog_task.sh
module(load="imjournal" StateFile="imjournal.state")
\$PreserveFQDN on

template(
  name="T_RFC5424"
  type="string"
  string="<%pri%>1 %timegenerated:::date-rfc3339% %hostname% %app-name% %procid% - - %msg%\\n"
)

*.* action(
  type="omfwd"
  target="${TARGET_HOST}"
  port="${TARGET_PORT}"
  protocol="tcp"
  Template="T_RFC5424"
  KeepAlive="on"
  ResendLastMSGOnReconnect="on"
)
EOF_CONF
}

remote_script='set -euo pipefail
FILE="$1"
TMP="$(mktemp)"
BACKUP_FILE="${FILE}.bak"

rm -f /etc/rsyslog.d/logstash.*

if command -v apt-get >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq rsyslog sed
elif command -v zypper >/dev/null 2>&1; then
  zypper --non-interactive --quiet install rsyslog sed
else
  echo "Kein unterstützter Paketmanager gefunden" >&2
  exit 1
fi

rm -f /var/log/syslog* /var/log/auth.log* /var/log/cron.log* /var/log/kern.log* /var/log/mail.log* /var/log/user.log*

for f in /etc/rsyslog.d/50-default.conf /etc/rsyslog.conf; do
  [[ -f "$f" ]] || continue
  sed -i -E \
    -e "/^[[:space:]]*#/! s|^([[:space:]]*)(\*\.\*;auth,authpriv\.none[[:space:]]+-?/var/log/syslog)|\1# \2|" \
    -e "/^[[:space:]]*#/! s|^([[:space:]]*)(auth,authpriv\.\*[[:space:]]+/var/log/auth\.log)|\1# \2|" \
    -e "/^[[:space:]]*#/! s|^([[:space:]]*)(cron\.\*[[:space:]]+-?/var/log/cron\.log)|\1# \2|" \
    -e "/^[[:space:]]*#/! s|^([[:space:]]*)(kern\.\*[[:space:]]+-?/var/log/kern\.log)|\1# \2|" \
    -e "/^[[:space:]]*#/! s|^([[:space:]]*)(mail\.\*[[:space:]]+-?/var/log/mail\.log)|\1# \2|" \
    -e "/^[[:space:]]*#/! s|^([[:space:]]*)(user\.\*[[:space:]]+-?/var/log/user\.log)|\1# \2|" \
    "$f"
done

if [[ -f "$FILE" ]]; then
  cp -f "$FILE" "$BACKUP_FILE"
fi

cat > "$TMP"
install -D -m 0644 "$TMP" "$FILE"
rm -f "$TMP"

if command -v rsyslogd >/dev/null 2>&1; then
  rsyslogd -N1
fi

if command -v systemctl >/dev/null 2>&1; then
  systemctl enable --now rsyslog >/dev/null 2>&1 || true
  systemctl restart rsyslog
else
  service rsyslog restart
fi
'

conf=$(build_rsyslog_conf)
info "Installiere Remote-Syslog auf ${Name} -> ${TARGET_HOST}:${TARGET_PORT}"
printf '%s' "$conf" | run_ssh_with_stdin "$remote_script" "$RSYSLOG_REMOTE_FILE"
